---
version: '3'
services:
  n1.east.example.net:
    container_name: n1-east
    image: nats
    dns_search: example.net
    environment:
      GATEWAY: c1
      NAME: n1-east
      ADVERTISE: localhost:10000
      REGION: region:east
    networks:
    - nats-cluster1
    - shared
    volumes:
    - "./configs/cluster-east.conf:/nats-server.conf"
    - "./data/n1-east:/data"
    ports:
    - 10000:4222
    - 10100:7422
  n2.east.example.net:
    container_name: n2-east
    image: nats
    dns_search: example.net
    labels:
      com.docker-tc.enabled: '1'
    environment:
      GATEWAY: c1
      NAME: n2-east
      ADVERTISE: localhost:10001
      REGION: region:east
    networks:
    - nats-cluster1
    - shared
    volumes:
    - "./configs/cluster-east.conf:/nats-server.conf"
    - "./data/n2-east:/data"
    ports:
    - 10001:4222
    - 10101:7422
  n3.east.example.net:
    container_name: n3-east
    image: nats
    dns_search: example.net
    environment:
      GATEWAY: c1
      NAME: n3-east
      ADVERTISE: localhost:10002
      REGION: region:east
    networks:
    - nats-cluster1
    - shared
    volumes:
    - "./configs/cluster-east.conf:/nats-server.conf"
    - "./data/n3-east:/data"
    ports:
    - 10002:4222
    - 10102:7422
  n1.central.example.net:
    container_name: n1-central
    image: nats
    dns_search: example.net
    environment:
      GATEWAY: c1
      NAME: n1-central
      ADVERTISE: localhost:10003
      REGION: region:central
    networks:
    - nats-cluster1
    - shared
    volumes:
    - "./configs/cluster-central.conf:/nats-server.conf"
    - "./data/n1-central:/data"
    ports:
    - 10003:4222
    - 10103:7422
  n2.central.example.net:
    container_name: n2-central
    image: nats
    dns_search: example.net
    environment:
      GATEWAY: c1
      NAME: n2-central
      ADVERTISE: localhost:10004
      REGION: region:central
    networks:
    - nats-cluster1
    - shared
    volumes:
    - "./configs/cluster-central.conf:/nats-server.conf"
    - "./data/n2-central:/data"
    ports:
    - 10004:4222
    - 10104:7422
  n3.central.example.net:
    container_name: n3-central
    image: nats
    dns_search: example.net
    environment:
      GATEWAY: c1
      NAME: n3-central
      ADVERTISE: localhost:10005
      REGION: region:central
    networks:
    - nats-cluster1
    - shared
    volumes:
    - "./configs/cluster-central.conf:/nats-server.conf"
    - "./data/n3-central:/data"
    ports:
    - 10005:4222
    - 10105:7422
  n1.west.example.net:
    container_name: n1-west
    image: nats
    dns_search: example.net
    environment:
      GATEWAY: c1
      NAME: n1-west
      ADVERTISE: localhost:10006
      REGION: region:west
    networks:
    - nats-cluster1
    - shared
    volumes:
    - "./configs/cluster-west.conf:/nats-server.conf"
    - "./data/n1-west:/data"
    ports:
    - 10006:4222
    - 10106:7422
  n2.west.example.net:
    container_name: n2-west
    image: nats
    dns_search: example.net
    environment:
      GATEWAY: c1
      NAME: n2-west
      ADVERTISE: localhost:10007
      REGION: region:west
    networks:
    - nats-cluster1
    - shared
    volumes:
    - "./configs/cluster-west.conf:/nats-server.conf"
    - "./data/n2-west:/data"
    ports:
    - 10007:4222
    - 10107:7422
  n3.west.example.net:
    container_name: n3-west
    image: nats
    dns_search: example.net
    environment:
      GATEWAY: c1
      NAME: n3-west
      ADVERTISE: localhost:10008
      REGION: region:west
    networks:
    - nats-cluster1
    - shared
    volumes:
    - "./configs/cluster-west.conf:/nats-server.conf"
    - "./data/n3-west:/data"
    ports:
    - 10008:4222
    - 10108:7422
networks:
  shared: {}
  nats-cluster1: {}
